# the conda channel is included by default
channels:
  - defaults
  - esri
  - pypi
dependencies:
  - geopandas
  - numpy
  - openpyxl
  - pandas
  - pyproj
  - requests
  - thefuzz
  - tqdm
  - xlrd
  - pip:
    # regular pip packages
    -  sodapy